#!/bin/bash

if [[ ! "$1" == "-"* ]] ; then
  REGEX="$1"
  shift 1
fi

GREP_OPTS="-i"

while getopts :c flag ; do
  case "$flag" in
    c)
      GREP_OPTS=""
      ;;
    ?)
      echo 'Invalid argument'
      exit 1
      ;;
  esac
done

if [ -z "$REGEX" ]; then
  shift $(( OPTIND-1 ))
  REGEX="$1"
fi

find . -type d -regextype posix-egrep -regex ".*\.(repo|git)" -prune -o -print | grep --color $GREP_OPTS $REGEX
