#!/bin/bash

BINDIR="$HOME/aur/bin"
SRCDIR="$HOME/aur/src"
cd $SRCDIR

for folder in $(pwd)/* ; do
	cd "$folder"
	echo $folder
	makepkg -sf --skippgpcheck && mv *.xz "$BINDIR/" && cd .. && rm -rf "$folder"
done
