#!/bin/bash

function yesterworkday() 
{ 
	echo "$(date +%u)"
    if [[ "1" == "$(date +%u)" ]]
    then 
        echo "last friday"
    else
        echo "yesterday"
    fi
}

repo forall -pc 'git log --after={1.days.ago}'
