#!/bin/bash

REC=false
[[ "$1" == "-R" || "$1" == "-r" ]] && REC=true
for d in $(ls -d */) ; do	
	cd "$d"
	if [ -d ".git" ]; then
		echo "Found git repository at $d"
        git checkout master
		git pull origin master
	fi
	cd ..
done
