#!/bin/bash

export AOSP_SRC=/run/media/pablo/storage/data/android/src/aosp
export USE_CCACHE=1
export OUT_DIR_COMMON_BASE=/run/media/pablo/storage/data/android/builds
export CCACHE_DIR=/run/media/pablo/storage/data/android/ccache

rm -rf $OUT_DIR_COMMON_BASE/aosp

. /usr/bin/virtualenvwrapper.sh
mkvirtualenv -p `which python2` python2
workon python2

cd $AOSP_SRC

. build/envsetup.sh

lunch aosp_hammerhead-user
make -j8

deactivate

echo "All done"
