#!/bin/bash

export JAVA_HOME=/opt/java6
export PATH=/opt/java6/bin:$PATH
export USE_CCACHE=1
export OUT_DIR_COMMON_BASE=/home/pablo/data/android/aosp/builds/generic
export CCACHE_DIR=/home/pablo/data/android/aosp/ccache
export AOSP_SRC=/run/media/pablo/storage/data/android/aosp/src

# pyversion 2
cd $AOSP_SRC

sudo ln -s -f /usr/bin/python2 /usr/local/bin/python
sudo ln -s -f $HOME/src/make-3.82/make /usr/local/bin/make

. build/envsetup.sh
lunch aosp_arm-eng

T="$(date +%s)"
make -j8
T="$(($(date +%s)-T))"

echo "Time in seconds: ${T}"
echo "All done!"
