#!/bin/bash

export CYANOGEN_SRC=/run/media/pablo/storage/data/android/src/cyanogen
export JAVA_HOME=/opt/java6
export PATH=/opt/java6/bin:$PATH
export USE_CCACHE=1
export OUT_DIR_COMMON_BASE=/home/pablo/data/android/builds/cyanogen
export CCACHE_DIR=/home/pablo/data/android/builds/cyanogen/ccache

pyversion 2

cd $CYANOGEN_SRC
. build/envsetup.sh

breakfast mako
cd vendor/cm
./get-prebuilts
croot
cd device/lge/mako
./extract-files.sh
croot

brunch mako
echo "All done"

pyversion 3
