#!/bin/bash

export CYANOGEN_SRC=/run/media/pablo/storage/data/android/cyanogen/src
export JAVA_HOME=/opt/java6
export PATH=/opt/java6/bin:$PATH
export USE_CCACHE=1
export OUT_DIR_COMMON_BASE=/home/pablo/data/android/cyanogen/builds
export CCACHE_DIR=/home/pablo/data/android/cyanogen/ccache

cd $CYANOGEN_SRC
. build/envsetup.sh

breakfast mako
cd vendor/cm
./get-prebuilts
croot
cd device/lge/mako
./extract-files.sh
croot

#T="$(date +%s)"
brunch mako
#T="$(($(date +%s)-T))"

#echo "Time in seconds: ${T}"
echo "All done"
