#!/bin/bash

if [ -z $1 ] ; then
	echo 'Please specify a device (mako/hammerhead)'
	exit 1
fi

device=$1
export PACMAN_SRC=/home/pablo/android/src/pacman
export JAVA_HOME=/opt/java6
export PATH=/opt/java6/bin:$PATH
export USE_CCACHE=1
export OUT_DIR_COMMON_BASE=/home/pablo/android/builds
export CCACHE_DIR=$HOME/.ccache
export PREBUILTS_DIR=/home/pablo/android/pacman

rm -rf $OUT_DIR_COMMON_BASE/pacman/*
mkdir -p "$OUT_DIR_COMMON_BASE"

sudo pyversion 3
cd $PACMAN_SRC
repo sync -j4

sudo pyversion 2
./build-pac.sh $device
sudo pyversion 3

cd $OUT_DIR_COMMON_BASE/pacman/target/product/$device
for f in pac_*zip* ; do
	cp $f "$PREBUILTS_DIR/"
done

echo "All done"
