#!/bin/env python

import sys
import getopt
import subprocess
import os

def execute_process(proc_args):
    split_args = proc_args.split(' ')
    subprocess.call(split_args)

def start_background(proc_args):
    split_args = proc_args.split(' ')
    proc_handle = subprocess.Popen(split_args)
    return proc_handle

def main():

    opts, args = getopt.getopt(sys.argv[1:], "h", ["help"])

    for arg in args:
        print(arg)

    execute_process("sudo rfkill unblock wifi")
    execute_process("sudo airmon-ng stop mon0")
    execute_process("sudo airmon-ng start " + os.environ['WIFI'])

    if not os.path.isdir('tmp'):
        os.makedirs('tmp')
    
    execute_process("sudo airodump-ng --encrypt WEP --output-format csv --write tmp/airodump mon0")
  

if __name__ == "__main__":
    main()