#!/bin/bash

PROJECT="$1"
USER="$2"
[ "" = "$USER" ] && USER="deployer"
HOST=""
if [ "$PROJECT" == "veenda" ] ; then
	HOST="162.209.101.215"
elif [ "$PROJECT" == "trumpit" ] ; then
	HOST="162.209.102.221"
else
	echo "Usage: racklogin PROJECT [ USER ]"
	exit -1
fi

echo "Sshing to $PROJECT at $USER@$HOST"

ssh "$USER@$HOST" 'sudo reboot' &
