#!/bin/bash

cd ~/src/trumpit/trumpit-api/db
rm -f dump.sql
pgbackup
cd ..
dropdb trumpit_dev
createdb trumpit_dev
psql -f db/dump.sql -U trumpit -d trumpit_dev
rm -f ~/src/trumpit/trumpit-api/db/dump.sql
