#!/bin/bash

find -name "*\.ai" | while IFS= read -r fname ; do
	DIR=$(dirname "$fname")
	COUNT=$(identify "$fname" | wc -l)
	COUNT=$((COUNT - 1))
	echo "$fname"
	for i in `seq 0 $COUNT`;
	do		
		convert -density 300 "$fname[$i]" "${fname%.ai}_${i}.png"
		convert -antialias "${fname%.ai}_${i}.png" \
		-fuzz 40% \
		-transparent white \
		 "${fname%.ai}_${i}.png" 
	done  
done

