#!/bin/bash
# generates mlocate database for home folder only
# exclude hidden directories
[ -f "$HOME/.locatedb/prunepaths" ] && rm "$HOME/.locatedb/prunepaths"
[ -f "$HOME/.locatedb/prunenames" ] && rm "$HOME/.locatedb/prunenames"

mkdir -p "$HOME/.locatedb"

# Ignore all hidden directories
hidden=$(ls -d $HOME/.*/)
# Add names you wish to prune
names=".hg .svn"

for dir in $hidden
do
	base=$(basename $dir)
	[ "$base" == ".." -o "$base" == "." ] || echo "$HOME/$base" >> "$HOME/.locatedb/prunepaths"
done
for name in $names
do
	echo $name >> "$HOME/.locatedb/prunenames"
done

updatedb -l 0 -o "$HOME/.locatedb/locate.db" -U "$HOME" --prunepaths \
 "$(cat $HOME/.locatedb/prunepaths)" --prunenames "$(cat $HOME/.locatedb/prunenames)"