#!/bin/bash

DBDIR=/home/pablo/updatedb


#/run/media/pablo/windows-8
sudo mount -U 98B05923B0590960
#/run/media/pablo/windows
sudo mount -U 1AF1D5B9051043CF


echo "root"
sudo updatedb --database-root / --output=$DBDIR/root.locatedb
echo "windows"
sudo updatedb --database-root /run/media/pablo/windows --output=$DBDIR/windows.locatedb
echo "windows-8"
sudo updatedb --database-root /run/media/pablo/windows-8 --output=$DBDIR/windows-8.locatedb
echo "storage"
sudo updatedb --database-root /run/media/pablo/storage --output=$DBDIR/storage.locatedb
echo "done"
