#!/bin/bash

find "${HOME}/.titanium" -type f -exec sed -i -r 's|python\.exec(.*)else="python([^2])|python\.exec\1else="python2\2|' {} \;
find "${HOME}/.titanium" -type f -exec sed -i -r 's|/usr/bin/env python([^2]\|$)|/usr/bin/env python2|' {} \;
find "${HOME}/.titanium" -type f -exec sed -i -r 's|/usr/bin/python([^2]\|$)|/usr/bin/python2|' {} \;
