#!/bin/bash

while getopts ":n:i:" opt; do

	case $opt in
		n)
			name=$OPTARG
			;;
		i)
			id=$OPTARG
			;;
		\?)
      		echo "Invalid option: -$OPTARG" >&2
      		exit 1
      		;;
      	:)
      		echo "Option -$OPTARG requires an argument." >&2
      		exit 1
      		;;
	esac
done

if [[ -z "$TEMPLATE_FOLDER" ]] || [[ -z "$name" ]] ; then
	echo "Usage: tireplace -n [NAME] -i [ID], TEMPLATE_FOLDER must be set"
	exit 1
fi

[[ -z "$id" ]] && id="com.pelluch.$name"


export MODULE_NAME="$name"
export MODULE_ID="$id"
export UPPER_MODULE_NAME="${MODULE_NAME^}"
export UUID=$(uuidgen)
out="$(pwd)/$MODULE_NAME"

for file in $(find $TEMPLATE_FOLDER -not -iwholename '*.git/*') ; do
	transformed=$(echo $file | perl -p -i -e 's/\$\{([^}]+)\}/defined $ENV{$1} ? $ENV{$1} : $&/eg' 2> /dev/null)
	if [ -f "$file" ] ; then
		file=${file#$TEMPLATE_FOLDER/}
		transformed=${transformed#$TEMPLATE_FOLDER/}
		perl -p -i -e 's/\$\{([^}]+)\}/defined $ENV{$1} ? $ENV{$1} : $&/eg' < "$TEMPLATE_FOLDER/$file" 2> /dev/null > "$MODULE_NAME/$transformed"
	else
		directory=${transformed#$TEMPLATE_FOLDER/}
		mkdir -p "$out/$directory"
    fi
done